"use client";

import Head from "next/head";
import { useState } from "react";
export default function Home() {
  const [num1, setNum1] = useState<string>("0");
  const [num2, setNum2] = useState<string>("0");
  const [result, setResult] = useState<number>(0);
  const add = () => {
    setResult(parseInt(num1) + parseInt(num2));
  };
  const subtract = () => {
    setResult(parseInt(num1) - parseInt(num2));
  };
  const multiply = () => {
    setResult(parseInt(num1) * parseInt(num2));
  };
  const divide = () => {
    setResult(parseInt(num1) / parseInt(num2));
  };
  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"result"} data-testid="result">
        {result}
      </div>
      <input
        type="number"
        className={"input"}
        data-testid="num1"
        value={num1}
        onChange={(e) => setNum1(e.target.value)}
      />
      <input
        type="number"
        className={"input"}
        data-testid="num2"
        value={num2}
        onChange={(e) => setNum2(e.target.value)}
      />
      <button onClick={add} className="button" data-testid="add">
        Add
      </button>
      <button onClick={subtract} className={"button"} data-testid="subtract">
        Subtract
      </button>
      <button onClick={multiply} className={"button"} data-testid="multiply">
        Multiply
      </button>
      <button onClick={divide} className={"button"} data-testid="divide">
        Divide
      </button>
    </div>
  );
}
